### ISSUE TITLE
no matching manifest for linux/amd64 in the manifest list entries

### ISSUE THREAD

**Issue by computermouth** [docker-library/hello-world#39]
```
$ docker pull arm32v7/hello-world
Using default tag: latest
latest: Pulling from arm32v7/hello-world
no matching manifest for linux/amd64 in the manifest list entries
```
Trying to pull the hello-world image for arm for the first time. I'm able to pull other arm containers just fine, seems specifically like a problem with this one.

**Comment by tianon** [comment]
This is because `hello-world:latest` is a manifest list -- the image you're looking for if you want the `arm32v7/hello-world` image on a non-ARM platform would be `arm32v7/hello-world:linux`. :+1:

(See "Shared Tags" vs "Simple Tags" in the image description: https://hub.docker.com/r/arm32v7/hello-world/)

**Comment by tianon** [comment]
I've filed https://github.com/docker-library/official-images/issues/3835 in order to have a central place to track this problem globally more directly. :+1: :heart:
