### ISSUE TITLE
Can not create a statically-linked rust executable with scratch image

### ISSUE THREAD

**Issue by vityafx** [docker-library/hello-world#44]
I am trying to create an image with my binary file (written in Rust) but I get different errors. This is my `Dockerfile`:

    FROM scratch
    COPY binary /
    COPY .env /
    COPY cert.pem /etc/ssl/
    ENV RUST_BACKTRACE 1
    CMD /binary

Building finishes fine but when I try to run it I get this:

    $ docker run binary
    docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/bin/sh\": stat /bin/sh: no such file or directory": unknown.
    ERRO[0000] error waiting for container: context canceled 

And this:

    $ docker run binary /binary
    standard_init_linux.go:195: exec user process caused "no such file or directory"

I have no idea what to do. The error message looks very odd to me. According to the [official docker documentation](https://docs.docker.com/develop/develop-images/baseimages/#create-a-simple-parent-image-using-scratch) it must work so.

System info: latest archlinux, docker:

    Docker version 18.02.0-ce, build fc4de447b5

P.S. Tested the same with C++ - works fine, with both clang and gcc.

**Comment by tianon** [comment]
You need to use the JSON syntax for CMD.

**Comment by wglambert** [comment]
Since the proposed resolution wasn't responded to in some time I'm assuming the issue is resolved

Given that the issue is more of a usability question, it would be more suited for [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).
