### ISSUE TITLE
Getting error while docker run hello-world

### ISSUE THREAD

**Issue by saikiranjayanthi** [docker-library/hello-world#52]
PS C:\Windows\system32> docker images hello-world
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.38/images/json?filters=%7B%22reference%22%3A%7B%22hel
lo-world%22%3Atrue%7D%7D: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon
configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docke
r daemon is not running.

**Comment by saikiranjayanthi** [comment]
This is my docker version.
Is anything we need to do 
PS C:\Windows\system32> docker --version
Docker version 18.06.1-ce, build 67f9a391

**Comment by wglambert** [comment]
>the docker client must be run elevated to connect.
Are you running Docker as an administrator?

**Comment by tianon** [comment]
Closing, since this is definitely an issue with your environment, not something wrong with the image.

In the future, these sorts of questions/requests would be more appropriately posted to [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).
