### ISSUE TITLE
Not able to pull hello world

### ISSUE THREAD

**Issue by ferdiaz8** [docker-library/hello-world#70]
When I run this command docker pull hello-world I get this:

Using default tag: latest
latest: Pulling from library/hello-world
no matching manifest for windows/amd64 10.0.17134 in the manifest list entries

Any advise?

**Comment by tianon** [comment]
Version 10.0.17134 corresponds to 1803, which if you look at https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/base-image-lifecycle was EOL in November of last year -- I'd suggest updating your host to 1809.

In the future, these sorts of questions/requests would be more appropriately posted to [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker) (since this isn't a problem with the `hello-world` image, but rather with your host environment).
