### ISSUE TITLE
hello world issue 

### ISSUE THREAD

**Issue by NayakManishh** [docker-library/hello-world#77]
I have installed docker properly and have Linux terminal also installed freshly in my windows10 pro system. After installing all things, when I started using my system, it shows me that the docker is still starting. I was not able to see any message regarding my hello world command in CMD.
How to fix this problem.Please, anyone, tell me

**Comment by wglambert** [comment]
If your Docker is still starting then it doesn't seem to be fully initialized and ready yet

You should try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum

**Comment by NayakManishh** [comment]
Then,how to install it correctly?
________________________________

**Comment by wglambert** [comment]
You've probably installed just fine but it may be in the initialization period of starting up on your system.
There are docs here for installing Docker on Windows https://docs.docker.com/docker-for-windows/install/

But I'm going to close the issue as it's not related to the image but is related to your environment

You could also search through issues over at https://github.com/docker/for-win or try the other help resources I linked before
