### ISSUE TITLE
Add support for riscv64 and arm32v6

### ISSUE THREAD

**Issue by MaxPeal** [docker-library/hello-world#79]
can we add support for riscv64 and arm32v6?
so we have hello-world for any possibly arch?

**Comment by tianon** [comment]
Regarding riscv64, I'd mirror my comment on https://github.com/docker-library/busybox/issues/87:

> We can certainly work on making sure it builds successfully, but we won't be merging anything officially unless/until https://github.com/docker-library/official-images/issues/8794 is resolved with some proper build/test hardware.

Regarding arm32v6, that's unfortunately not an architecture that Debian officially supports, which is the build environment for our binaries (since it has the most supported architectures).  That being said, the ARMv5 binary should work fine there, and given we don't do much more than "print a string and exit successfully" I'm not sure whether floating point optimizations are actually relevant here?

Additionally, the number of arm32v6 systems that exist make me really question whether it's worth going to more effort to support (like getting a cross-compiler from elsewhere); the only popular boards I'm aware of are the Raspberry Pi 1 and Raspberry Pi Zero.  If we were to "support" this, I think we would do so by labelling the `arm32v5` build as `arm32v6`, which I don't think actually provides much value, since most popular container runtimes should already walk down the list of supported architectures in the manifest list on an `arm32v6` device and run the `arm32v5` image instead (barring minor bugs like the one I fixed in containerd in https://github.com/containerd/containerd/pull/4530).
