### ISSUE TITLE
Why assembly / binary?

### ISSUE THREAD

**Issue by ericandrewlewis** [docker-library/hello-world#8]
Why does this image use binary / assembly instead of a higher-level script?

**Comment by yosifkit** [comment]
That is to make it a super tiny image, it is only `960 B` (yes, just bytes). If we used a script we would also have to include the interpreter and the libraries that it requires.

**Comment by tianon** [comment]
Indeed, it's also used in the Docker documentation as an example of how to make a hyper-minimal container using `FROM scratch`.

**Comment by ericandrewlewis** [comment]
That makes sense, I figured this kind of reasoning was behind it.

While building up material for a new user workshop, I came across this repo. It might be good to spell out the reasoning behind the repository. The usage here seems rather advanced, and may confuse new users who think that hello world examples are good educational starters.

**Comment by ncopa** [comment]
> it is only 960 B (yes, just bytes).

and of those, the message itself is 801 bytes. :)

**Comment by tianon** [comment]
See also https://github.com/tianon/dockerfiles/tree/master/true where this was adapted from (which is where I played with both C and Go to try to make something tiny, and obviously ASM won quite handily).

**Comment by benatkin** [comment]
The README could explain that assembly is a good choice both because it's tiny (link to true) and because it doesn't endorse any compiled language :)

**Comment by arnabsc** [comment]
Please advise why I am facing the below error while trying to do docker-pull ?



docker pull hello-world
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)



Is there any manual process to copy the hello world image on my Ubuntu VM and the install it ?

**Comment by yosifkit** [comment]
@arnabsc, your problem is not really related to this issue.  Your issue sounds like a network connection issue.  If you can't pull images from Docker Hub, you could always git clone and build the images yourself.  In the future, it'd be better to post questions like this in [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).

As for this issue, I'lll close it. We no longer use assembly :cry:.  But we do have 7 architectures plus windows!
